//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Series_Blog.Entitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblComment
    {
        public int CommentId { get; set; }
        public string CommentNameSurname { get; set; }
        public string CommentMail { get; set; }
        public string CommnetContext { get; set; }
        public Nullable<int> CommnetBlog { get; set; }
    
        public virtual TblBlog TblBlog { get; set; }
    }
}
